#!/bin/bash

if [[ -z "$XM_USERNAME" ]]; then
  echo "ERROR: Missing XM_USERNAME env"
  exit 1
fi

if [[ -z "$XM_PASSWORD" ]]; then
  echo "ERROR: Missing XM_PASSWORD env"
  exit 1
fi

cat - > /opt/app/settings.cfg <<EOF
# Generated by container start.sh
[SeriousCast]
username=$XM_USERNAME
password=$XM_PASSWORD
hostname=${PUBLISH_HOST:-`hostname`}
url_scheme=${URL_SCHEME:-http}
port=${LISTEN_PORT:-30000}
publish_port=${PUBLISH_PORT:-30000}
EOF

python3 /opt/app/server.py
